/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplicacionempleo;

import com.mongodb.BasicDBList;
import com.mongodb.BasicDBObject;
import com.mongodb.client.FindIterable;
import static com.mongodb.client.model.Filters.eq;
import static com.mongodb.client.model.Updates.combine;
import static com.mongodb.client.model.Updates.set;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ScrollPaneConstants;
import javax.swing.table.DefaultTableModel;
import org.bson.Document;

/**
 *
 * @author Carlos Nuila
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupSexo = new javax.swing.ButtonGroup();
        buttonGroupContrato = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel_personas = new javax.swing.JPanel();
        jb_crearTpersona = new javax.swing.JButton();
        jb_modTpersona = new javax.swing.JButton();
        jb_deleteTpersona = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jt_nombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jt_apellido = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jrb_masculino = new javax.swing.JRadioButton();
        jrb_femenino = new javax.swing.JRadioButton();
        jrb_noDecirlo = new javax.swing.JRadioButton();
        jt_numeroIdentidad = new javax.swing.JTextField();
        jSpinEdad = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jcheck_familia = new javax.swing.JCheckBox();
        jcheckEnfermedad = new javax.swing.JCheckBox();
        jt_enfermedad = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jcheckCarcel = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAcademicos = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableEmpleos = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTablePuestos = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jrb_permanente = new javax.swing.JRadioButton();
        jrb_temporal = new javax.swing.JRadioButton();
        jrb_porProyecto = new javax.swing.JRadioButton();
        jLabel17 = new javax.swing.JLabel();
        jSpinSalario = new javax.swing.JSpinner();
        jb_guardar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jtBuscarPersona = new javax.swing.JTextField();
        jb_buscarPersona = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jb_crearTEmpresa = new javax.swing.JButton();
        jb_modTEmpresa = new javax.swing.JButton();
        jb_deleteTEmpresa = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jtBuscarEmpresa = new javax.swing.JTextField();
        jb_buscarEmpresa = new javax.swing.JButton();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jt_nombreEmpresa = new javax.swing.JTextField();
        jt_rtnEmpresa = new javax.swing.JTextField();
        jt_directorEmpresa = new javax.swing.JTextField();
        jt_direccionEmpresa = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable_Empleos = new javax.swing.JTable();
        jb_guardarEmpresa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Inicio", jPanel3);

        jPanel_personas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jb_crearTpersona.setText("Crear");
        jb_crearTpersona.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_crearTpersonaMouseClicked(evt);
            }
        });
        jPanel_personas.add(jb_crearTpersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 75, -1));

        jb_modTpersona.setText("Modificar");
        jb_modTpersona.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_modTpersonaMouseClicked(evt);
            }
        });
        jPanel_personas.add(jb_modTpersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(467, 11, -1, -1));

        jb_deleteTpersona.setText("Eliminar");
        jb_deleteTpersona.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_deleteTpersonaMouseClicked(evt);
            }
        });
        jPanel_personas.add(jb_deleteTpersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 11, 75, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Nombre:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jt_nombre.setEditable(false);
        jPanel1.add(jt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 140, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Apellido:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jt_apellido.setEditable(false);
        jPanel1.add(jt_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 140, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Sexo:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Edad:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Especifique:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Numero Identidad:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, -1, -1));

        buttonGroupSexo.add(jrb_masculino);
        jrb_masculino.setText("Masculino");
        jrb_masculino.setEnabled(false);
        jPanel1.add(jrb_masculino, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, -1, -1));

        buttonGroupSexo.add(jrb_femenino);
        jrb_femenino.setSelected(true);
        jrb_femenino.setText("Femenino");
        jrb_femenino.setEnabled(false);
        jPanel1.add(jrb_femenino, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, -1));

        buttonGroupSexo.add(jrb_noDecirlo);
        jrb_noDecirlo.setText("Prefiero no decirlo");
        jrb_noDecirlo.setEnabled(false);
        jPanel1.add(jrb_noDecirlo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, -1, -1));

        jt_numeroIdentidad.setEditable(false);
        jPanel1.add(jt_numeroIdentidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, 143, -1));

        jSpinEdad.setModel(new javax.swing.SpinnerNumberModel(15, 14, null, 1));
        jSpinEdad.setEnabled(false);
        jPanel1.add(jSpinEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 54, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Personales:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Académicos:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("Familiares:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jcheck_familia.setText("Vive con familia");
        jcheck_familia.setEnabled(false);
        jPanel1.add(jcheck_familia, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        jcheckEnfermedad.setText("Padece Enfermedad");
        jcheckEnfermedad.setEnabled(false);
        jcheckEnfermedad.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcheckEnfermedadItemStateChanged(evt);
            }
        });
        jPanel1.add(jcheckEnfermedad, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        jt_enfermedad.setEditable(false);
        jPanel1.add(jt_enfermedad, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 140, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Sanitarios:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jcheckCarcel.setText("¿Ha estado arrestado?");
        jcheckCarcel.setEnabled(false);
        jPanel1.add(jcheckCarcel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, -1, -1));

        jTableAcademicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nivel de Estudios", "Lugar", "Promedio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableAcademicos.setEnabled(false);
        jTableAcademicos.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableAcademicos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 420, 120));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("Legales:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, -1, -1));

        jTabbedPane2.addTab("Datos", jPanel1);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableEmpleos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Empresa", "Años", "Puesto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableEmpleos.setEnabled(false);
        jTableEmpleos.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTableEmpleos);
        if (jTableEmpleos.getColumnModel().getColumnCount() > 0) {
            jTableEmpleos.getColumnModel().getColumn(1).setPreferredWidth(20);
        }

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 630, 120));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("Laborales:");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Salario:");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, -1, -1));

        jTablePuestos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Puesto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTablePuestos.setEnabled(false);
        jScrollPane3.setViewportView(jTablePuestos);

        jPanel4.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 210, 120));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("Preferencias:");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setText("Puestos que puede realizar:");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        buttonGroupContrato.add(jrb_permanente);
        jrb_permanente.setSelected(true);
        jrb_permanente.setText("Permanente");
        jrb_permanente.setEnabled(false);
        jPanel4.add(jrb_permanente, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, -1, -1));

        buttonGroupContrato.add(jrb_temporal);
        jrb_temporal.setText("Temporal");
        jrb_temporal.setEnabled(false);
        jPanel4.add(jrb_temporal, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 250, -1, -1));

        buttonGroupContrato.add(jrb_porProyecto);
        jrb_porProyecto.setText("Por Proyecto");
        jrb_porProyecto.setEnabled(false);
        jPanel4.add(jrb_porProyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 250, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setText("Tipo de Contrato:");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, -1, -1));

        jSpinSalario.setModel(new javax.swing.SpinnerNumberModel(1000.0d, 1000.0d, null, 1.0d));
        jSpinSalario.setEnabled(false);
        jPanel4.add(jSpinSalario, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, 140, -1));

        jb_guardar.setText("Guardar");
        jb_guardar.setEnabled(false);
        jb_guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_guardarMouseClicked(evt);
            }
        });
        jPanel4.add(jb_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 320, 120, -1));

        jTabbedPane2.addTab("Datos Laborales", jPanel4);

        jPanel_personas.add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 52, 680, 400));

        jLabel2.setText("Buscar:");
        jPanel_personas.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 15, -1, -1));

        jtBuscarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtBuscarPersonaActionPerformed(evt);
            }
        });
        jPanel_personas.add(jtBuscarPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 12, 191, -1));

        jb_buscarPersona.setText("Buscar");
        jb_buscarPersona.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_buscarPersonaMouseClicked(evt);
            }
        });
        jPanel_personas.add(jb_buscarPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 11, 75, -1));

        jTabbedPane1.addTab("Personas", jPanel_personas);

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jb_crearTEmpresa.setText("Crear");
        jb_crearTEmpresa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_crearTEmpresaMouseClicked(evt);
            }
        });
        jPanel5.add(jb_crearTEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 22, 75, -1));

        jb_modTEmpresa.setText("Modificar");
        jb_modTEmpresa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_modTEmpresaMouseClicked(evt);
            }
        });
        jPanel5.add(jb_modTEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(494, 22, -1, -1));

        jb_deleteTEmpresa.setText("Eliminar");
        jb_deleteTEmpresa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_deleteTEmpresaMouseClicked(evt);
            }
        });
        jPanel5.add(jb_deleteTEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(587, 22, 75, -1));

        jLabel18.setText("Buscar:");
        jPanel5.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 26, -1, -1));
        jPanel5.add(jtBuscarEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 23, 191, -1));

        jb_buscarEmpresa.setText("Buscar");
        jb_buscarEmpresa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_buscarEmpresaMouseClicked(evt);
            }
        });
        jb_buscarEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_buscarEmpresaActionPerformed(evt);
            }
        });
        jPanel5.add(jb_buscarEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 22, 75, -1));

        jLabel19.setText("Nombre");

        jLabel20.setText("RTN");

        jLabel21.setText("Director");

        jLabel22.setText("Direccion");

        jt_nombreEmpresa.setEnabled(false);
        jt_nombreEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_nombreEmpresaActionPerformed(evt);
            }
        });

        jt_rtnEmpresa.setEnabled(false);

        jt_directorEmpresa.setEnabled(false);

        jt_direccionEmpresa.setEnabled(false);
        jt_direccionEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_direccionEmpresaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22))
                .addGap(37, 37, 37)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jt_nombreEmpresa)
                    .addComponent(jt_rtnEmpresa)
                    .addComponent(jt_directorEmpresa)
                    .addComponent(jt_direccionEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(407, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jt_nombreEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jt_rtnEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jt_directorEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jt_direccionEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55))
        );

        jTabbedPane3.addTab("Datos", jPanel6);

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable_Empleos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Categoria", "Puesto", "Edad", "Estudios", "Prision", "Experiencia", "Sueldo", "Contrato"
            }
        ));
        jTable_Empleos.setEnabled(false);
        jScrollPane4.setViewportView(jTable_Empleos);

        jPanel7.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 690, 268));

        jb_guardarEmpresa.setText("Guardar");
        jb_guardarEmpresa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_guardarEmpresaMouseClicked(evt);
            }
        });
        jPanel7.add(jb_guardarEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 280, 109, 42));

        jTabbedPane3.addTab("Empleos", jPanel7);

        jPanel5.add(jTabbedPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 91, 700, 365));

        jTabbedPane1.addTab("Empresas", jPanel5);

        jPanel2.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 480));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_crearTpersonaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_crearTpersonaMouseClicked
        // TODO add your handling code here:
        seleccionPer = "Crear";
        reestablecerCampos(true);
        jtBuscarPersona.setText("");
    }//GEN-LAST:event_jb_crearTpersonaMouseClicked

    private void jcheckEnfermedadItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcheckEnfermedadItemStateChanged
        if (jcheckEnfermedad.isSelected()) {
            jt_enfermedad.setEditable(true);
        } else {
            jt_enfermedad.setText("");
            jt_enfermedad.setEditable(false);
        }
    }//GEN-LAST:event_jcheckEnfermedadItemStateChanged

    private void jb_guardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_guardarMouseClicked
        // TODO add your handling code here:
        String sexo = "femenino";
        if (jrb_masculino.isSelected()) {
            sexo = "masculino";
        } else {
            if (jrb_noDecirlo.isSelected()) {
                sexo = "otro";
            }
        }
        boolean viveFamilia = false;
        if (jcheck_familia.isSelected()) {
            viveFamilia = true;
        }
        boolean enCarcel = false;
        if (jcheckCarcel.isSelected()) {
            enCarcel = true;
        }
        boolean enfermedad = false;
        if (jcheckEnfermedad.isSelected()) {
            enfermedad = true;
        }
        BasicDBObject enfermedadDoc = new BasicDBObject("tiene_enfermedad", enfermedad);
        if (enfermedad) {
            enfermedadDoc.append("especifica", jt_enfermedad.getText());
        }

        String[] campoAcademicos = {"nivelEstudios", "lugar", "promedio"};
        String[] campoEmpleos = {"empresa", "años", "puesto"};
        String[] campoPuestos = {"puesto"};

        String tipoContract = "Permanente";
        if (jrb_temporal.isSelected()) {
            tipoContract = "Temporal";
        } else {
            if (jrb_porProyecto.isSelected()) {
                tipoContract = "Por Proyecto";
            }
        }

        connect.conectar("personas");

        if (seleccionPer.equals("Crear")) {
            Document persona = new Document("identidad", jt_numeroIdentidad.getText())
                    .append("nombre", jt_nombre.getText())
                    .append("apellido", jt_apellido.getText())
                    .append("edad", jSpinEdad.getValue())
                    .append("sexo", sexo)
                    .append("vive_Familia", viveFamilia)
                    .append("carcel", enCarcel)
                    .append("enfermedad", enfermedadDoc)
                    .append("estudios", ingresarTabla((DefaultTableModel) jTableAcademicos.getModel(), campoAcademicos))
                    .append("laborales", ingresarTabla((DefaultTableModel) jTableEmpleos.getModel(), campoEmpleos))
                    .append("puestoCapaz", ingresarTabla((DefaultTableModel) jTablePuestos.getModel(), campoPuestos))
                    .append("tipoContrato", tipoContract)
                    .append("salarioDeseado", jSpinSalario.getValue());
            connect.insertar(persona);
            JOptionPane.showMessageDialog(this, "Creó una persona exitosamente", "Información", JOptionPane.INFORMATION_MESSAGE);
        } else {
            connect.getCollection().updateOne(eq("identidad", jtBuscarPersona.getText()),
                    combine(set("nombre", jt_nombre.getText()),
                            set("apellido", jt_apellido.getText()),
                            set("edad", jSpinEdad.getValue()),
                            set("sexo", sexo),
                            set("vive_Familia", viveFamilia),
                            set("carcel", enCarcel),
                            set("enfermedad", enfermedadDoc),
                            set("estudios", ingresarTabla((DefaultTableModel) jTableAcademicos.getModel(), campoAcademicos)),
                            set("laborales", ingresarTabla((DefaultTableModel) jTableEmpleos.getModel(), campoEmpleos)),
                            set("puestoCapaz", ingresarTabla((DefaultTableModel) jTablePuestos.getModel(), campoPuestos)),
                            set("tipoContrato", tipoContract),
                            set("salarioDeseado", jSpinSalario.getValue())));
            JOptionPane.showMessageDialog(this, "Se actualizó una persona exitosamente", "Información", JOptionPane.INFORMATION_MESSAGE);
        }
        jtBuscarPersona.setText("");
        connect.cerrarConexion();
        reestablecerCampos(false);
    }//GEN-LAST:event_jb_guardarMouseClicked

    private void jb_modTpersonaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_modTpersonaMouseClicked
        // TODO add your handling code here:
        if (!jtBuscarPersona.getText().equals("")) {
            seleccionPer = "Modificar";

            jTableAcademicos.setEnabled(true);
            jTableEmpleos.setEnabled(true);
            jTablePuestos.setEnabled(true);

            jt_nombre.setEditable(true);
            jt_apellido.setEditable(true);

            jrb_femenino.setEnabled(true);
            jrb_masculino.setEnabled(true);
            jrb_noDecirlo.setEnabled(true);

            jSpinEdad.setEnabled(true);

            jcheck_familia.setEnabled(true);

            jcheckEnfermedad.setEnabled(true);
            if (jcheckEnfermedad.isSelected()) {
                jt_enfermedad.setEditable(true);
            }

            jcheckCarcel.setEnabled(true);

            jrb_permanente.setEnabled(true);
            jrb_temporal.setEnabled(true);
            jrb_porProyecto.setEnabled(true);

            jSpinSalario.setEnabled(true);

            jb_guardar.setEnabled(true);
        } else {
            JOptionPane.showMessageDialog(this, "Debe encontrar a una persona primero", "Información", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jb_modTpersonaMouseClicked

    private void jb_deleteTpersonaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_deleteTpersonaMouseClicked
        // TODO add your handling code here:
        if (!jtBuscarPersona.getText().equals("")) {
            connect.conectar("personas");
            connect.getCollection().deleteOne(eq("identidad", jtBuscarPersona.getText()));
            connect.cerrarConexion();
            reestablecerCampos(false);
            jtBuscarPersona.setText("");
            JOptionPane.showMessageDialog(this, "Eliminó a una persona", "Información", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Debe encontrar a una persona primero", "Información", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jb_deleteTpersonaMouseClicked

    private void jb_buscarPersonaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_buscarPersonaMouseClicked
        // TODO add your handling code here:
        reestablecerCampos(false);
        if (!jtBuscarPersona.getText().equals("")) {
            connect.conectar("personas");
            FindIterable<Document> findIterable = connect.getCollection()
                    .find(eq("identidad", jtBuscarPersona.getText()));
            if (findIterable.first() == null) {
                JOptionPane.showMessageDialog(this, "No se encontró lo que buscaba", "Información", JOptionPane.INFORMATION_MESSAGE);
                jtBuscarPersona.setText("");
            } else {
                String nombre = "", apellido = "", sexo = "", enfermedadEspecifica = "", tipoContrato = "";
                int edad = 0;
                double salario = 0;
                boolean familia = false, carcel = false, tiene_enfermedad = false;
                ArrayList<Object> iterador = new ArrayList<>();

                for (Document doc : findIterable) {
                    nombre = doc.getString("nombre");
                    apellido = doc.getString("apellido");
                    sexo = doc.getString("sexo");
                    edad = doc.getInteger("edad");
                    familia = doc.getBoolean("vive_Familia");
                    carcel = doc.getBoolean("carcel");
                    Document enfermedad = (Document) doc.get("enfermedad");
                    tiene_enfermedad = enfermedad.getBoolean("tiene_enfermedad");
                    if (tiene_enfermedad) {
                        enfermedadEspecifica = enfermedad.getString("especifica");
                    }
                    tipoContrato = doc.getString("tipoContrato");
                    salario = doc.getDouble("salarioDeseado");

                    jt_nombre.setText(nombre);
                    jt_numeroIdentidad.setText(jtBuscarPersona.getText());
                    jt_apellido.setText(apellido);
                    jSpinEdad.setValue(edad);

                    if (sexo.equals("masculino")) {
                        jrb_femenino.setSelected(false);
                        jrb_masculino.setSelected(true);
                    } else {
                        if (sexo.equals("otro")) {
                            jrb_femenino.setSelected(false);
                            jrb_noDecirlo.setSelected(true);
                        }
                    }

                    if (familia) {
                        jcheck_familia.setSelected(true);
                    }
                    if (carcel) {
                        jcheckCarcel.setSelected(true);
                    }
                    if (tiene_enfermedad) {
                        jcheckEnfermedad.setSelected(true);
                        jt_enfermedad.setText(enfermedadEspecifica);
                        jt_enfermedad.setEditable(false);
                    }

                    if (tipoContrato.equals("Temporal")) {
                        jrb_permanente.setSelected(false);
                        jrb_temporal.setSelected(true);
                    } else {
                        if (tipoContrato.equals("Por Proyecto")) {
                            jrb_permanente.setSelected(false);
                            jrb_porProyecto.setSelected(true);
                        }
                    }

                    jSpinSalario.setValue(salario);

                    String[] campoAcademicos = {"nivelEstudios", "lugar", "promedio"};
                    String[] campoEmpleos = {"empresa", "años", "puesto"};
                    String[] campoPuestos = {"puesto"};

                    iterador = (ArrayList<Object>) doc.get("estudios");
                    llenarTabla(jTableAcademicos, iterador, campoAcademicos);
                    iterador = (ArrayList<Object>) doc.get("laborales");
                    llenarTabla(jTableEmpleos, iterador, campoEmpleos);
                    iterador = (ArrayList<Object>) doc.get("puestoCapaz");
                    llenarTabla(jTablePuestos, iterador, campoPuestos);
                    connect.cerrarConexion();
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "No puede estar vacío el campo", "Información", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jb_buscarPersonaMouseClicked

    private void jb_crearTEmpresaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_crearTEmpresaMouseClicked
        jt_nombreEmpresa.setEnabled(true);
        jt_rtnEmpresa.setEnabled(true);
        jt_direccionEmpresa.setEnabled(true);
        jt_directorEmpresa.setEnabled(true);
        jTable_Empleos.setEnabled(true);
        seleccionEMP = "Crear";
    }//GEN-LAST:event_jb_crearTEmpresaMouseClicked

    private void jb_modTEmpresaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_modTEmpresaMouseClicked

        if (!jtBuscarEmpresa.getText().equals("")) {
            seleccionEMP = "Modificar";

            jTable_Empleos.setEnabled(true);

            jt_nombreEmpresa.setEnabled(true);
            jt_rtnEmpresa.setEnabled(true);
            jt_direccionEmpresa.setEnabled(true);
            jt_directorEmpresa.setEnabled(true);

        } else {
            JOptionPane.showMessageDialog(this, "Debe encontrar a una persona primero", "Información", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jb_modTEmpresaMouseClicked

    private void jb_deleteTEmpresaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_deleteTEmpresaMouseClicked
        if (!jtBuscarEmpresa.getText().equals("")) {
            connect.conectar("empresas");
            connect.getCollection().deleteOne(eq("rtn", jtBuscarEmpresa.getText()));
            connect.cerrarConexion();
            reestablecerCampos(false);
            jtBuscarEmpresa.setText("");
            JOptionPane.showMessageDialog(this, "Eliminó a una persona", "Información", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Debe encontrar a una persona primero", "Información", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jb_deleteTEmpresaMouseClicked

    private void jb_buscarEmpresaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_buscarEmpresaMouseClicked
        if (!jtBuscarEmpresa.getText().equals("")) {
            connect.conectar("empresas");
            FindIterable<Document> findIterable = connect.getCollection()
                    .find(eq("rtn", jtBuscarEmpresa.getText()));
            if (findIterable.first() == null) {
                JOptionPane.showMessageDialog(this, "No se encontró lo que buscaba", "Información", JOptionPane.INFORMATION_MESSAGE);
                jtBuscarPersona.setText("");
            } else {
                String nombre = "", rtn = "", direccion = "", director = "";
                ArrayList<Object> iterador = new ArrayList<>();
                for (Document doc : findIterable) {
                    nombre = doc.getString("nombre");
                    rtn = doc.getString("rtn");
                    director = doc.getString("director");
                    direccion = doc.getString("direccion");

                    jt_nombreEmpresa.setText(nombre);
                    jt_rtnEmpresa.setText(rtn);
                    jt_directorEmpresa.setText(director);
                    jt_direccionEmpresa.setText(direccion);

                    String[] camposEmpleos = {"nombre", "categoria", "puesto", "edad", "estudios", "prision", "experiencia", "sueldo", "contrato"};
                    iterador = (ArrayList<Object>) doc.get("empleos");
                    llenarTablaEmpleo(jTable_Empleos, iterador, camposEmpleos);

                    connect.cerrarConexion();
                }

            }
        } else {
            JOptionPane.showMessageDialog(this, "No puede estar vacío el campo", "Información", JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_jb_buscarEmpresaMouseClicked

    private void jb_buscarEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_buscarEmpresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_buscarEmpresaActionPerformed

    private void jt_nombreEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_nombreEmpresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_nombreEmpresaActionPerformed

    private void jt_direccionEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_direccionEmpresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_direccionEmpresaActionPerformed

    private void jb_guardarEmpresaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_guardarEmpresaMouseClicked

        String[] camposEmpleos = {"nombre", "categoria", "puesto", "edad", "estudios", "prision", "experiencia", "sueldo", "contrato"};
        connect.conectar("empresas");
        if (seleccionEMP.equals("Crear")) {
            Document empresa = new Document("nombre", jt_nombreEmpresa.getText())
                    .append("rtn", jt_rtnEmpresa.getText())
                    .append("director", jt_directorEmpresa.getText())
                    .append("direccion", jt_direccionEmpresa.getText())
                    .append("empleos", ingresarTablaEmpleo((DefaultTableModel) jTable_Empleos.getModel(), camposEmpleos));
            connect.insertar(empresa);
            JOptionPane.showMessageDialog(this, "Creó una empresa exitosamente", "Información", JOptionPane.INFORMATION_MESSAGE);
        } else {
            connect.getCollection().updateOne(eq("rtn", jtBuscarEmpresa.getText()),
                    combine(set("nombre", jt_nombre.getText()),
                            set("rtn", jt_rtnEmpresa.getText()),
                            set("director", jt_directorEmpresa.getText()),
                            set("direccion", jt_direccionEmpresa.getText()),
                            set("empleos", ingresarTablaEmpleo((DefaultTableModel) jTable_Empleos.getModel(), camposEmpleos))));
            JOptionPane.showMessageDialog(this, "Se actualizó una empresa exitosamente", "Información", JOptionPane.INFORMATION_MESSAGE);
        }
        jtBuscarEmpresa.setText("");
        connect.cerrarConexion();
    }//GEN-LAST:event_jb_guardarEmpresaMouseClicked

    private void jtBuscarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtBuscarPersonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtBuscarPersonaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    public void rehacerTablaAcademico() {
        jTableAcademicos.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
                    {null, null, null},
                    {null, null, null},
                    {null, null, null},
                    {null, null, null},
                    {null, null, null},
                    {null, null, null},
                    {null, null, null},
                    {null, null, null},
                    {null, null, null},
                    {null, null, null}
                },
                new String[]{
                    "Nivel de Estudios", "Lugar", "Promedio"
                }
        ) {
            Class[] types = new Class[]{
                java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }
        });
        jTableAcademicos.setColumnSelectionAllowed(true);
        jTableAcademicos.setEnabled(false);
        jTableAcademicos.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableAcademicos);
    }

    public void rehacerTablaPuestos() {
        jTablePuestos.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
                    {null},
                    {null},
                    {null},
                    {null},
                    {null},
                    {null}
                },
                new String[]{
                    "Puesto"
                }
        ) {
            Class[] types = new Class[]{
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }
        });
        jTablePuestos.setEnabled(false);
        jScrollPane3.setViewportView(jTablePuestos);
    }

    public void rehacerTablaLaborales() {
        jTableEmpleos.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
                    {null, null, null},
                    {null, null, null},
                    {null, null, null},
                    {null, null, null},
                    {null, null, null},
                    {null, null, null},
                    {null, null, null},
                    {null, null, null},
                    {null, null, null},
                    {null, null, null}
                },
                new String[]{
                    "Empresa", "Años", "Puesto"
                }
        ) {
            Class[] types = new Class[]{
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }
        });
        jTableEmpleos.setEnabled(false);
        jTableEmpleos.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTableEmpleos);
        if (jTableEmpleos.getColumnModel().getColumnCount() > 0) {
            jTableEmpleos.getColumnModel().getColumn(1).setPreferredWidth(20);
        }
    }

    public void reestablecerCampos(boolean habilitar) {
        rehacerTablaAcademico();
        jTableAcademicos.setEnabled(habilitar);
        rehacerTablaLaborales();
        jTableEmpleos.setEnabled(habilitar);
        rehacerTablaPuestos();
        jTablePuestos.setEnabled(habilitar);

        jt_nombre.setEditable(habilitar);
        jt_nombre.setText("");

        jt_apellido.setEditable(habilitar);
        jt_apellido.setText("");

        jrb_femenino.setEnabled(habilitar);
        jrb_femenino.setSelected(true);

        jrb_masculino.setEnabled(habilitar);
        jrb_masculino.setSelected(false);

        jrb_noDecirlo.setEnabled(habilitar);
        jrb_noDecirlo.setSelected(false);

        jt_numeroIdentidad.setEditable(habilitar);
        jt_numeroIdentidad.setText("");

        jSpinEdad.setValue(15);
        jSpinEdad.setEnabled(habilitar);

        jcheck_familia.setEnabled(habilitar);
        jcheck_familia.setSelected(false);

        jcheckEnfermedad.setEnabled(habilitar);
        jcheckEnfermedad.setSelected(false);
        jt_enfermedad.setText("");
        jt_enfermedad.setEditable(false);

        jcheckCarcel.setEnabled(habilitar);
        jcheckCarcel.setSelected(false);

        jrb_permanente.setSelected(true);
        jrb_permanente.setEnabled(habilitar);

        jrb_temporal.setSelected(false);
        jrb_temporal.setEnabled(habilitar);

        jrb_porProyecto.setSelected(false);
        jrb_porProyecto.setEnabled(habilitar);

        jSpinSalario.setValue(1000);
        jSpinSalario.setEnabled(habilitar);

        jb_guardar.setEnabled(habilitar);
    }

    public BasicDBList ingresarTabla(DefaultTableModel modeloTabla, String[] campos) {
        int columnas = modeloTabla.getColumnCount();
        int filas = modeloTabla.getRowCount();
        BasicDBList lista = new BasicDBList();
        for (int i = 0; i < filas; i++) {
            if (modeloTabla.getValueAt(i, 0) != null) {
                BasicDBObject obj = new BasicDBObject();
                for (int j = 0; j < columnas; j++) {
                    obj.put(campos[j], modeloTabla.getValueAt(i, j));
                }
                lista.add(obj);
            } else {
                i = filas;
            }
        }
        return lista;
    }

    public BasicDBList ingresarTablaEmpleo(DefaultTableModel modeloTabla, String[] campos) {
        int columnas = modeloTabla.getColumnCount();
        int filas = modeloTabla.getRowCount();
        BasicDBList lista = new BasicDBList();

        for (int i = 0; i < filas; i++) {
            if (modeloTabla.getValueAt(i, 0) != null) {
                BasicDBObject obj = new BasicDBObject();
                for (int j = 0; j < columnas; j++) {
                    if (modeloTabla.getValueAt(i, j) == null) {

                    } else {
                        if (j == 2) {
                            BasicDBList puestos = new BasicDBList();
                            String[] puestos2 = modeloTabla.getValueAt(i, j).toString().split(",");
                            for (String puesto : puestos2) {
                                puestos.add(puesto);
                            }
                            obj.put(campos[j], puestos);
                        } else {
                            obj.put(campos[j], modeloTabla.getValueAt(i, j));
                        }
                    }
                }
                lista.add(obj);
            } else {
                i = filas;
            }
        }
        return lista;
    }

    public void llenarTabla(JTable tabla, ArrayList<Object> iterador, String[] campos) {
        DefaultTableModel modelo = (DefaultTableModel) tabla.getModel();
        int limite = modelo.getRowCount();
        for (int i = 0; i < limite; i++) {
            modelo.removeRow(0);
        }

        ArrayList<Object> fila = new ArrayList<>();
        for (Object doc : iterador) {
            for (int i = 0; i < campos.length; i++) {
                fila.add(((Document) doc).get(campos[i]));
            }
            modelo.addRow(fila.toArray());
            fila.clear();
        }
        tabla.setModel(modelo);

    }

    public void llenarTablaEmpleo(JTable tabla, ArrayList<Object> iterador, String[] campos) {
        DefaultTableModel modelo = (DefaultTableModel) tabla.getModel();
        int limite = modelo.getRowCount();
        for (int i = 0; i < limite; i++) {
            modelo.removeRow(0);
        }

        ArrayList<Object> fila = new ArrayList<>();
        for (Object doc : iterador) {
            for (int i = 0; i < campos.length; i++) {
                if (i == 2) {
                    String Puestos = "";
                    ArrayList<Object> list = (ArrayList<Object>) ((Document) doc).get(campos[i]);
                    for (int k=0;k<list.size();k++) {
                        if (k == list.size()-1) {
                            Puestos += list.get(k).toString();
                        } else {
                            Puestos += list.get(k).toString() + ",";
                        }
                    }
                    fila.add(Puestos);
                } else {
                    fila.add(((Document) doc).get(campos[i]));
                }
            }
            modelo.addRow(fila.toArray());
            fila.clear();
        }
        tabla.setModel(modelo);

    }
    String seleccionEMP = "";
    String seleccionPer = "";
    Conexion connect = new Conexion();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupContrato;
    private javax.swing.ButtonGroup buttonGroupSexo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel_personas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSpinner jSpinEdad;
    private javax.swing.JSpinner jSpinSalario;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTable jTableAcademicos;
    private javax.swing.JTable jTableEmpleos;
    private javax.swing.JTable jTablePuestos;
    private javax.swing.JTable jTable_Empleos;
    private javax.swing.JButton jb_buscarEmpresa;
    private javax.swing.JButton jb_buscarPersona;
    private javax.swing.JButton jb_crearTEmpresa;
    private javax.swing.JButton jb_crearTpersona;
    private javax.swing.JButton jb_deleteTEmpresa;
    private javax.swing.JButton jb_deleteTpersona;
    private javax.swing.JButton jb_guardar;
    private javax.swing.JButton jb_guardarEmpresa;
    private javax.swing.JButton jb_modTEmpresa;
    private javax.swing.JButton jb_modTpersona;
    private javax.swing.JCheckBox jcheckCarcel;
    private javax.swing.JCheckBox jcheckEnfermedad;
    private javax.swing.JCheckBox jcheck_familia;
    private javax.swing.JRadioButton jrb_femenino;
    private javax.swing.JRadioButton jrb_masculino;
    private javax.swing.JRadioButton jrb_noDecirlo;
    private javax.swing.JRadioButton jrb_permanente;
    private javax.swing.JRadioButton jrb_porProyecto;
    private javax.swing.JRadioButton jrb_temporal;
    private javax.swing.JTextField jtBuscarEmpresa;
    private javax.swing.JTextField jtBuscarPersona;
    private javax.swing.JTextField jt_apellido;
    private javax.swing.JTextField jt_direccionEmpresa;
    private javax.swing.JTextField jt_directorEmpresa;
    private javax.swing.JTextField jt_enfermedad;
    private javax.swing.JTextField jt_nombre;
    private javax.swing.JTextField jt_nombreEmpresa;
    private javax.swing.JTextField jt_numeroIdentidad;
    private javax.swing.JTextField jt_rtnEmpresa;
    // End of variables declaration//GEN-END:variables
}
