/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplicacionempleo;

import com.mongodb.BasicDBList;
import com.mongodb.BasicDBObject;
import com.mongodb.MongoClient;
import com.mongodb.MongoClientURI;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoDatabase;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.bson.Document;

/**
 *
 * @author Carlos Nuila
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupSexo = new javax.swing.ButtonGroup();
        buttonGroupContrato = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel_personas = new javax.swing.JPanel();
        jb_crearTpersona = new javax.swing.JButton();
        jb_modTpersona = new javax.swing.JButton();
        jb_deleteTpersona = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jt_nombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jt_apellido = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jrb_masculino = new javax.swing.JRadioButton();
        jrb_femenino = new javax.swing.JRadioButton();
        jrb_noDecirlo = new javax.swing.JRadioButton();
        jt_numeroIdentidad = new javax.swing.JTextField();
        jSpinEdad = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jcheck_familia = new javax.swing.JCheckBox();
        jcheckEnfermedad = new javax.swing.JCheckBox();
        jt_enfermedad = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jcheckCarcel = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAcademicos = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableEmpleos = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTablePuestos = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jrb_permanente = new javax.swing.JRadioButton();
        jrb_temporal = new javax.swing.JRadioButton();
        jrb_porProyecto = new javax.swing.JRadioButton();
        jLabel17 = new javax.swing.JLabel();
        jSpinSalario = new javax.swing.JSpinner();
        jb_guardar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jtBuscarPersona = new javax.swing.JTextField();
        jb_buscarPersona = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 715, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 452, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Inicio", jPanel3);

        jPanel_personas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jb_crearTpersona.setText("Crear");
        jb_crearTpersona.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_crearTpersonaMouseClicked(evt);
            }
        });
        jPanel_personas.add(jb_crearTpersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 75, -1));

        jb_modTpersona.setText("Modificar");
        jPanel_personas.add(jb_modTpersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(467, 11, -1, -1));

        jb_deleteTpersona.setText("Eliminar");
        jPanel_personas.add(jb_deleteTpersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 11, 75, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Nombre:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jt_nombre.setEditable(false);
        jPanel1.add(jt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 140, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Apellido:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jt_apellido.setEditable(false);
        jPanel1.add(jt_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 140, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Sexo:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Edad:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Especifique:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Numero Identidad:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, -1, -1));

        buttonGroupSexo.add(jrb_masculino);
        jrb_masculino.setText("Masculino");
        jrb_masculino.setEnabled(false);
        jPanel1.add(jrb_masculino, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, -1, -1));

        buttonGroupSexo.add(jrb_femenino);
        jrb_femenino.setSelected(true);
        jrb_femenino.setText("Femenino");
        jrb_femenino.setEnabled(false);
        jPanel1.add(jrb_femenino, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, -1));

        buttonGroupSexo.add(jrb_noDecirlo);
        jrb_noDecirlo.setText("Prefiero no decirlo");
        jrb_noDecirlo.setEnabled(false);
        jPanel1.add(jrb_noDecirlo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, -1, -1));

        jt_numeroIdentidad.setEditable(false);
        jPanel1.add(jt_numeroIdentidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, 143, -1));

        jSpinEdad.setModel(new javax.swing.SpinnerNumberModel(15, 14, null, 1));
        jSpinEdad.setEnabled(false);
        jPanel1.add(jSpinEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 54, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Personales:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Académicos:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("Familiares:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jcheck_familia.setText("Vive con familia");
        jcheck_familia.setEnabled(false);
        jPanel1.add(jcheck_familia, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        jcheckEnfermedad.setText("Padece Enfermedad");
        jcheckEnfermedad.setEnabled(false);
        jcheckEnfermedad.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcheckEnfermedadItemStateChanged(evt);
            }
        });
        jPanel1.add(jcheckEnfermedad, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        jt_enfermedad.setEditable(false);
        jPanel1.add(jt_enfermedad, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 140, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Sanitarios:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jcheckCarcel.setText("¿Ha estado en la arrestado?");
        jcheckCarcel.setEnabled(false);
        jPanel1.add(jcheckCarcel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, -1, -1));

        jTableAcademicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nivel de Estudios", "Lugar", "Promedio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableAcademicos.setColumnSelectionAllowed(true);
        jTableAcademicos.setEnabled(false);
        jTableAcademicos.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableAcademicos);
        jTableAcademicos.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 420, 120));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("Legales:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, -1, -1));

        jTabbedPane2.addTab("Datos", jPanel1);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableEmpleos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Empresa", "Años", "Puesto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableEmpleos.setEnabled(false);
        jTableEmpleos.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTableEmpleos);
        if (jTableEmpleos.getColumnModel().getColumnCount() > 0) {
            jTableEmpleos.getColumnModel().getColumn(1).setPreferredWidth(20);
        }

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 630, 120));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("Laborales:");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Salario:");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, -1, -1));

        jTablePuestos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Puesto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTablePuestos.setEnabled(false);
        jScrollPane3.setViewportView(jTablePuestos);

        jPanel4.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 210, 120));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("Preferencias:");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setText("Puestos que puede realizar:");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        buttonGroupContrato.add(jrb_permanente);
        jrb_permanente.setSelected(true);
        jrb_permanente.setText("Permanente");
        jrb_permanente.setEnabled(false);
        jPanel4.add(jrb_permanente, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, -1, -1));

        buttonGroupContrato.add(jrb_temporal);
        jrb_temporal.setText("Temporal");
        jrb_temporal.setEnabled(false);
        jPanel4.add(jrb_temporal, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 250, -1, -1));

        buttonGroupContrato.add(jrb_porProyecto);
        jrb_porProyecto.setText("Por Proyecto");
        jrb_porProyecto.setEnabled(false);
        jPanel4.add(jrb_porProyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 250, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setText("Tipo de Contrato:");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, -1, -1));

        jSpinSalario.setModel(new javax.swing.SpinnerNumberModel(1000.0d, 1000.0d, null, 1.0d));
        jSpinSalario.setEnabled(false);
        jPanel4.add(jSpinSalario, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, 140, -1));

        jb_guardar.setText("Guardar");
        jb_guardar.setEnabled(false);
        jb_guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_guardarMouseClicked(evt);
            }
        });
        jPanel4.add(jb_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 320, 120, -1));

        jTabbedPane2.addTab("Datos Laborales", jPanel4);

        jPanel_personas.add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 52, 690, 400));

        jLabel2.setText("Buscar:");
        jPanel_personas.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 15, -1, -1));
        jPanel_personas.add(jtBuscarPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 12, 191, -1));

        jb_buscarPersona.setText("Buscar");
        jPanel_personas.add(jb_buscarPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 11, 75, -1));

        jTabbedPane1.addTab("Personas", jPanel_personas);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 715, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 452, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Empresas", jPanel5);

        jPanel2.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 480));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_crearTpersonaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_crearTpersonaMouseClicked
        // TODO add your handling code here:
        seleccionPer = "Crear";
        rehacerTablaAcademico();
        jTableAcademicos.setEnabled(true);
        rehacerTablaLaborales();
        jTableEmpleos.setEnabled(true);
        rehacerTablaPuestos();
        jTablePuestos.setEnabled(true);

        jt_nombre.setEditable(true);
        jt_nombre.setText("");

        jt_apellido.setEditable(true);
        jt_apellido.setText("");

        jrb_femenino.setEnabled(true);
        jrb_femenino.setSelected(true);

        jrb_masculino.setEnabled(true);
        jrb_masculino.setSelected(false);

        jrb_noDecirlo.setEnabled(true);
        jrb_noDecirlo.setSelected(false);

        jt_numeroIdentidad.setEditable(true);
        jt_numeroIdentidad.setText("");

        jSpinEdad.setValue(15);
        jSpinEdad.setEnabled(true);

        jcheck_familia.setEnabled(true);
        jcheck_familia.setSelected(false);

        jcheckEnfermedad.setEnabled(true);
        jcheckEnfermedad.setSelected(false);
        jt_enfermedad.setText("");
        jt_enfermedad.setEditable(false);

        jcheckCarcel.setEnabled(true);
        jcheckCarcel.setSelected(false);

        jrb_permanente.setSelected(true);
        jrb_permanente.setEnabled(true);

        jrb_temporal.setSelected(false);
        jrb_temporal.setEnabled(true);

        jrb_porProyecto.setSelected(false);
        jrb_porProyecto.setEnabled(true);

        jSpinSalario.setValue(1000);
        jSpinSalario.setEnabled(true);

        jb_guardar.setEnabled(true);
    }//GEN-LAST:event_jb_crearTpersonaMouseClicked

    private void jcheckEnfermedadItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcheckEnfermedadItemStateChanged
        if (jcheckEnfermedad.isSelected()) {
            jt_enfermedad.setEditable(true);
        } else {
            jt_enfermedad.setText("");
            jt_enfermedad.setEditable(false);
        }
    }//GEN-LAST:event_jcheckEnfermedadItemStateChanged

    private void jb_guardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_guardarMouseClicked
        // TODO add your handling code here:
        String sexo = "femenino";
        if (jrb_masculino.isSelected()) {
            sexo = "masculino";
        } else {
            if (jrb_noDecirlo.isSelected()) {
                sexo = "Otro";
            }
        }
        boolean viveFamilia = false;
        if (jcheck_familia.isSelected()) {
            viveFamilia = true;
        }
        boolean enCarcel = false;
        if (jcheckCarcel.isSelected()) {
            enCarcel = true;
        }
        boolean enfermedad = false;
        if (jcheckEnfermedad.isSelected()) {
            enfermedad = true;
        }
        BasicDBObject enfermedadDoc = new BasicDBObject("tiene_enfermedad", enfermedad);
        if (enfermedad) {
            enfermedadDoc.append("Nombre", jt_enfermedad.getText());
        }

        String[] campoAcademicos = {"nivelEstudios", "lugar", "promedio"};
        String[] campoEmpleos = {"empresa", "años", "puesto"};
        String[] campoPuestos = {"puesto"};

        String tipoContract = "Permanente";
        if (jrb_temporal.isSelected()) {
            tipoContract = "Temporal";
        } else {
            if (jrb_porProyecto.isSelected()) {
                tipoContract = "Por Proyecto";
            }
        }

        MongoClient mongoClient = new MongoClient(
                new MongoClientURI(
                        "mongodb+srv://eagle:aldisparo@cluster0-g2ngr.mongodb.net/test?authSource=admin&replicaSet=Cluster0-shard-0&readPreference=primary&appname=MongoDB%20Compass%20Community&ssl=true"
                )
        );
        MongoDatabase database = mongoClient.getDatabase("proyecto");
        MongoCollection<Document> collection = database.getCollection("personas");

        if (seleccionPer.equals("Crear")) {
            Document persona = new Document("identidad", jt_numeroIdentidad.getText())
                    .append("nombre", jt_nombre.getText())
                    .append("apellido", jt_apellido.getText())
                    .append("edad", jSpinEdad.getValue())
                    .append("sexo", sexo)
                    .append("vive_Familia", viveFamilia)
                    .append("carcel", enCarcel)
                    .append("enfermedad", enfermedadDoc)
                    .append("estudios", ingresarTabla((DefaultTableModel) jTableAcademicos.getModel(), campoAcademicos))
                    .append("laborales", ingresarTabla((DefaultTableModel) jTableEmpleos.getModel(), campoEmpleos))
                    .append("puestoCapaz", ingresarTabla((DefaultTableModel) jTablePuestos.getModel(), campoPuestos))
                    .append("tipoContrato", tipoContract)
                    .append("salarioDeseado", jSpinSalario.getValue());
            collection.insertOne(persona);
            JOptionPane.showMessageDialog(this, "Creó una persona exitosamente", "Información", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jb_guardarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    public void rehacerTablaAcademico() {
        jTableAcademicos.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
                    {null, null, null},
                    {null, null, null},
                    {null, null, null},
                    {null, null, null},
                    {null, null, null},
                    {null, null, null},
                    {null, null, null},
                    {null, null, null},
                    {null, null, null},
                    {null, null, null}
                },
                new String[]{
                    "Nivel de Estudios", "Lugar", "Promedio"
                }
        ) {
            Class[] types = new Class[]{
                java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }
        });
        jTableAcademicos.setColumnSelectionAllowed(true);
        jTableAcademicos.setEnabled(false);
        jTableAcademicos.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableAcademicos);
        jTableAcademicos.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
    }

    public void rehacerTablaPuestos() {
        jTablePuestos.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
                    {null},
                    {null},
                    {null},
                    {null},
                    {null},
                    {null}
                },
                new String[]{
                    "Puesto"
                }
        ) {
            Class[] types = new Class[]{
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }
        });
        jTablePuestos.setEnabled(false);
        jScrollPane3.setViewportView(jTablePuestos);
    }

    public void rehacerTablaLaborales() {
        jTableEmpleos.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
                    {null, null, null},
                    {null, null, null},
                    {null, null, null},
                    {null, null, null},
                    {null, null, null},
                    {null, null, null},
                    {null, null, null},
                    {null, null, null},
                    {null, null, null},
                    {null, null, null}
                },
                new String[]{
                    "Empresa", "Años", "Puesto"
                }
        ) {
            Class[] types = new Class[]{
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }
        });
        jTableEmpleos.setEnabled(false);
        jTableEmpleos.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTableEmpleos);
        if (jTableEmpleos.getColumnModel().getColumnCount() > 0) {
            jTableEmpleos.getColumnModel().getColumn(1).setPreferredWidth(20);
        }
    }

    public BasicDBList ingresarTabla(DefaultTableModel modeloTabla, String[] campos) {
        int columnas = modeloTabla.getColumnCount();
        int filas = modeloTabla.getRowCount();
        BasicDBList lista = new BasicDBList();
        BasicDBObject obj = new BasicDBObject();
        for (int i = 0; i < filas; i++) {
            if (modeloTabla.getValueAt(i, 0) != null) {
                for (int j = 0; j < columnas; j++) {
                    obj.append(campos[j], modeloTabla.getValueAt(i, j));
                }
                lista.add(obj);
            } else {
                i = filas;
            }
        }
        return lista;
    }

    String seleccionPer = "";
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupContrato;
    private javax.swing.ButtonGroup buttonGroupSexo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel_personas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSpinner jSpinEdad;
    private javax.swing.JSpinner jSpinSalario;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTableAcademicos;
    private javax.swing.JTable jTableEmpleos;
    private javax.swing.JTable jTablePuestos;
    private javax.swing.JButton jb_buscarPersona;
    private javax.swing.JButton jb_crearTpersona;
    private javax.swing.JButton jb_deleteTpersona;
    private javax.swing.JButton jb_guardar;
    private javax.swing.JButton jb_modTpersona;
    private javax.swing.JCheckBox jcheckCarcel;
    private javax.swing.JCheckBox jcheckEnfermedad;
    private javax.swing.JCheckBox jcheck_familia;
    private javax.swing.JRadioButton jrb_femenino;
    private javax.swing.JRadioButton jrb_masculino;
    private javax.swing.JRadioButton jrb_noDecirlo;
    private javax.swing.JRadioButton jrb_permanente;
    private javax.swing.JRadioButton jrb_porProyecto;
    private javax.swing.JRadioButton jrb_temporal;
    private javax.swing.JTextField jtBuscarPersona;
    private javax.swing.JTextField jt_apellido;
    private javax.swing.JTextField jt_enfermedad;
    private javax.swing.JTextField jt_nombre;
    private javax.swing.JTextField jt_numeroIdentidad;
    // End of variables declaration//GEN-END:variables
}
